#### Config for CB-Spider PoC ####

## Config for OpenStack ##
openstack:

  # OpenStack Credential Info
  domain_name: {domain_name}
  # identity_endpoint: http://{ip}/identity/v3   # for devstak-queens
  identity_endpoint: http://{ip}:5000/v3
  password: {password}
  project_id: {project_id}
  username: {username}
  region: {region}

  # OpenStack VM Deployment Info
  vm_name: {vm_name}
  image_id: {image_id}
  flavor_id: {flavor_id}
  network_id: {network_id}
  security_groups: {security_groups}
  keypair_name: {keypair_name}

  # OpenStack Test VM Info
  server_id: {server_id}

  image_info:
    name: mcb_custom_image.iso

  keypair_info:
    name: mcb-test-key

  security_group_info:
    name: mcb-test-security

  vnet_info:
    name: mcb-test-vnet

  subnet_info:
      id: {subnet_id}

  router_info:
    name: mcb-router
    gateway_id: {gateway_id}
    adminstatup: true

## Config for AZURE ##
azure:

  # Azure Credential Info
  client_id: xxx
  client_secret: xxx
  tenant_id: xxx
  subscription_id: xxx

  # Azure VM Deployment Info
  location: koreacentral
  vm_size: Standard_B1ls
  image:
    publisher: Canonical
    offer: UbuntuServer
    sku: 16.04.0-LTS
    version: latest

  os:
    compute_name: mcb-test-vm
    admin_username: cbarista
    admin_password: xxx

  nic:
    id: /subscriptions/f1548292-2be3-4acd-84a4-6df079160846/resourceGroups/cb-resource-group/providers/Microsoft.Network/networkInterfaces/cb-nic

  # Azure Test VM Info
  group_name: cb-resource-group
  vm_name: vm-name

  image_info:
    group_name: cb-resource-group
    name: image-name

  public_ip:
    group_name: cb-resource-group
    name: ip_name

  security_group:
    group_name: cb-resource-group
    name: sec_name

  virtual_network:
    group_name: cb-resource-group
    name: vnet_name

  network_interface:
    group_name: cb-resource-group
    name: nic_name



aws:

  # AWS Credential Info
  aws_access_key_id: None
  aws_secret_access_key: None
  region: ap-northeast-2

  # AMI
  image_id: ami-047f7b46bd6dd5d84

  # EC2
  ec2_instance_id: i-04f1693f5e94c1c79
  base_name: mcloud-barista
  instance_type: t2.micro
  #  key_name: mcloud-barista-keypair
  key_name: powerkimkeypair
  min_count: 1
  max_count: 1

  # Network
  subnet_id: subnet-c3b446ab
  security_group_id: sg-07ec42983dbc5e36e


## Config for Cloudit ##
cloudit:

  # Cloudit Credential Info
  user_id: cloudit
  password: cloudit
  identity_endpoint: http://stg.cloudit.co.kr:9090
  #  identity_endpoint: http://192.168.130.5:9090
  #  auth_token: ddd8e54a5bac82eea3de7c347ff8a253d0dc563d
  auth_token: 05ae4abeebf06cc29a1d5c96c5fc4459abf7ee1d
  #  tenant_id: tnt0008
  tenant_id: tnt0009
  server_id: 7b35148e-b033-4749-a29e-12beddaebbfa

  # Cloudit VM Create Info
  vm_info:
    template_id: 2813a6ed-66f8-4041-9cfa-2cb5cb416520
    spec_id: 1c38e438-ede9-4df5-8775-2ce791698924
    name: mcb-vm
    root_password: xxx
    subnet_addr: 10.0.8.0
    sec_groups: b2be62e7-fd29-43ff-b008-08ae736e092a
    description: mcb-test-vm
    protection: 0

  # Cloudit Resource Create Info
  resource:
    image:
      name: mcb-test-img
    public_ip:
      name: mcb-test-pubip
    security_group:
      name: mcb-test-sg
    vnet_info:
      name: mcb-test-vnet
    vnic_info:
      vm_id: 025e5edc-54ad-4b98-9292-6eeca4c36a6d
      mac: AC:DE:48:00:08:05
    vm_info:
      name: mcb-test-vm
